name: SCSS to CSS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Sass
        run: npm install -g sass
        
      - name: Clear Sass cache
        run: sass --no-cache
  
      - name: Compile SCSS to CSS
        run: sass --update scss/:css/
